### ISSUE TITLE
Running DVID service

### ISSUE THREAD

**Issue by huanxiang** [janelia-flyem/dvid#145]
Hello, 

I has just installed the DVID using both docker and the ubuntu installation script, which seems to be successful. However, when I tried to run dvid serve /config/config.toml. I got the following error: 

Unable to initialize datastore: Error loading metadata: Error loading new local ids: Bad value returned for new ids.  Length 0 bytes!

Here is my config file. Is there anything wrong?

Thanks a lot!
Huanxiang

```toml
# Example configuration for DVID

[server]
httpAddress = "127.0.0.1:8000"
rpcAddress = "127.0.0.1:8001"
webClient = "/dvid-console"

# to return Timing-Allow-Origin headers in response
# allowTiming = true

# How new data instance ids are generated.
# Is one of "random" or "sequential".  If "sequential" can set "start_instance_id" property.
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.

# Email server to use for notifications and server issuing email-based authorization tokens.
#[email]
#notify = ["foo@someplace.edu"] # Who to send email in case of panic
#username = 
#password = 
#server = 
#port = 25

[logging]
logfile = "/demo/logs/dvid.log"
max_log_size = 500 # MB
max_log_age = 30   # days

[store]   
    # Stores can be specified in three ways (default setting required):
    # store.default  = default storage engine if not otherwise specified
    # store.metadata = configuration for metadata store
    # store.datatype = storage engine to use for the given "datatype"
    # store."name:uuid" = storage engine for a particular data instance, 
    #   where uuid is the full UUID of the repo's root.
    
    [store.default]
    engine = "basholeveldb"
    path = "/demo/dbs/basholeveldb"

    [store.imagetile]
    engine = "basholeveldb"
    path = "/data/tiles" 
```
