### ISSUE TITLE
dvid gbucket backend doesn't work

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#321]
I can't launch dvid with the following toml:

```toml
[server]
httpAddress = ":8090"
rpcAddress = ":8091"
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.
webClient = "/groups/flyem/proj/cluster/miniforge/envs/flyem37/http/dvid-web-console"
webDefaultFile = "index.html"

note = """
{"source": "gs://cryo-clem-samples"}
"""

[logging]
# We assume each worker is run from a unique directory,
# so this logfile name need not be unique.
logfile = "dvid.log"
max_log_size = 500 # MB
max_log_age = 30   # days
[store]
    [store.mutable]
        engine = "gbucket"
        bucket= "cryo-clem-samples" # Repo UUID: 4842811737dd4e62ba09303671b265e7
```

I get the following error:

```
$ dvid -verbose serve dvid.toml
Sending log messages to: /groups/flyem/data/scratchspace/flyemflows/copygrayscale/hess/cryo-clem-samples/upload-em/dvid.log
unable to initialize datastore: Metadata store "google cloud storage, bucket cryo-clem-samples" is not an ordered key-value store!
```

I know this works in earlier versions of dvid (fe31c124390b7e46ec7726b38f9f09cf16ba77a6).
