### ISSUE TITLE
gocloud.dev git repo

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#346]
Recently, the following lines were added to [`scripts/get-go-dependencies.sh`][1]:

```bash
# Go Cloud Development Kit
go get gocloud.dev
go get github.com/google/wire
go get golang.org/x/xerrors
```

As usual, a corresponding entry was added to [`scripts/conda-recipe/meta.yaml`][2] to speed up the build by caching the git repo of the new dependency:

```yaml
  # go cloud dev kit
  - git_url: https://gocloud.dev
    git_tag: master
    folder:  src/gocloud.dev
```

...but unfortunately `https://gocloud.dev` is not a git repo, so the build fails.  I'm not sure what git repo we should be caching instead.  For now, I've simply commented out the new lines in `meta.yaml`.  We should fix that eventually.

[1]: https://github.com/janelia-flyem/dvid/blob/019fc76b09c8e423f11e9cd9f04f8da4532b5b2d/scripts/get-go-dependencies.sh#L157-L160
[2]: https://github.com/janelia-flyem/dvid/blob/82e7f0c627513d980976d2b018cda26fc17a50ee/scripts/conda-recipe/meta.yaml#L221-L224
